server:
  port: 8081

  tomcat:
    basedir: build/tomcat
    accesslog:
      enabled: true

spring:
  profiles:
    active: default
  main:
    banner-mode: 'off'

  mvc:
    throw-exception-if-no-handler-found: true
    log-resolved-exception: false

  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 32MB

  jackson:
    serialization:
      indent_output: true
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
      write-null-map-values: false
    deserialization:
      fail-on-unknown-properties: false
      fail-on-ignored-properties: false

  jpa:
    open-in-view: false
    properties:
      hibernate:
        use_sql_comments: false
        format_sql: true
        show_sql: false
        jdbc:
          lob:
            non_contextual_creation: true

  # Datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/micro_auth
    username: micro
    password: micro1234

  security:
    oauth2:
      client:
        preEstablishedRedirectUri: true
        useCurrentUri: false
        provider:
      resource:
        filter-order: 3
        jwt:
          key-value: |
            -----BEGIN PUBLIC KEY-----
            MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL1Ff5N8Yj8qwf33oIKc82VUpvHfemXD
            /aCRQo572CsRxeiYFCPd4UrTjPrKeID19SUK2Gt0SII7BqDw8yZ8oMcCAwEAAQ==
            -----END PUBLIC KEY-----
---
spring:
  profiles: test

  jpa.properties.hibernate.show_sql: true
---
spring:
  profiles: dev

  jpa.properties.hibernate.show_sql: true
