server:
  port: 8081

  tomcat:
    basedir: build/tomcat
    accesslog:
      enabled: true

spring:
  profiles:
    active: default
  main:
    banner-mode: 'off'

  mvc:
    throw-exception-if-no-handler-found: true
    log-resolved-exception: false

  http:
    multipart:
      max-file-size: 32MB
      max-request-size: 32MB

  # Jackson
  jackson:
    serialization:
      indent_output: true
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
      write-null-map-values: false
    deserialization:
      fail-on-unknown-properties: false
      fail-on-ignored-properties: false

  jpa:
    open-in-view: false
    properties:
      hibernate:
        use_sql_comments: false
        format_sql: true
        show_sql: false

  # Datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/micro_auth
    username: micro
    password: micro1234

    tomcat:
      initial-size: 3
      max-active: 20
      min-idle: 3
      max-idle: 15
      max-wait: 10000
      max-age: 60000
      validation-query: SELECT 1
      validation-query-timeout: 3
      validation-interval: 15000
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false

security:
  oauth2:
    client:
      preEstablishedRedirectUri: true
      useCurrentUri: false
    resource:
      filter-order: 3
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL1Ff5N8Yj8qwf33oIKc82VUpvHfemXD
          /aCRQo572CsRxeiYFCPd4UrTjPrKeID19SUK2Gt0SII7BqDw8yZ8oMcCAwEAAQ==
          -----END PUBLIC KEY-----
---
spring:
  profiles: test

  jpa.properties.hibernate.show_sql: true
---
spring:
  profiles: dev

  jpa.properties.hibernate.show_sql: true
